import random

#the number generated by random floating numbers would be betweem 0<=x<1.0

rando = random.random() # - it generates a floating number module between 0.0 to 1.0
#the first random refers to the module and the second random refers to the random function. 
#few modules do not take any input and everytime i run the code, it generates random floating number
print(rando)
# we can also perform operations on it : 
rando1 = random.random()*10
print(rando1)
rando2 = random.uniform(1,10) # generates a random floating number within the range.
print(rando2)
#this functions generates a floating value where it is < than a & >b